"""asd

Revision ID: 0ac8af8501e1
Revises: 5e150362c97d
Create Date: 2026-04-03 17:23:58.560837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac8af8501e1'
down_revision: Union[str, Sequence[str], None] = '5e150362c97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telegram_avatar_file_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_avatar_file_id')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
