"""asd

Revision ID: 5e150362c97d
Revises: 
Create Date: 2026-04-03 16:26:52.583066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e150362c97d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_other', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_draft', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('direction_id', sa.Uuid(), nullable=True),
    sa.Column('custom_direction_label', sa.String(length=512), nullable=True),
    sa.Column('user_status', sa.String(length=32), nullable=True),
    sa.Column('school_grade', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=512), nullable=True),
    sa.Column('student_course', sa.Integer(), nullable=True),
    sa.Column('university', sa.String(length=512), nullable=True),
    sa.Column('specialty', sa.String(length=512), nullable=True),
    sa.Column('has_olympiad_experience', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('olympiad_description', sa.Text(), nullable=True),
    sa.Column('olympiad_links', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('team_seeking_mode', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject_id', name='uq_identity_provider_subject')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_identities')
    op.drop_table('users')
    op.drop_table('directions')
    # ### end Alembic commands ###
